version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    environment:
      - DEPLOY_ENV=development
      - PORT=9000
    networks:
      - dockernet
    ports:
      - '9000:9000'
    working_dir: /root
    volumes:
      - ./src:/root/src
    #network_mode: "host"

networks:
  dockernet:
    external: true
